{% set name = "fpsim2" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chembl/FPSim2/archive/{{ version }}.tar.gz
  sha256: 554bba0fa802e157a9edffc621c0c264210167f602d06cc478b9588b42d45b61

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.14
    - pybind11 >=2.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytables >=3.4.4
    - rdkit >=2022.03.3
    - scipy
    - tqdm
    - sqlalchemy >=1.4.7

test:
  imports:
    - FPSim2
  source_files:
    - tests/**
    - pytest.ini
  requires:
    - pytest
  commands:
    - pytest --verbose tests/

about:
  home: https://github.com/chembl/FPSim2
  license: MIT
  license_file: LICENSE
  summary: Simple package for fast molecular similarity searches

extra:
  recipe-maintainers:
    - eloyfelix
    - hadim
